SELECT DISTINCT
	ON (COMPANY_NAME) COMPANY_NAME,
	NET_PRODUCTS
FROM
	(
		SELECT
			YEAR,
			COMPANY_NAME,
			(
				COUNT(*) FILTER (
					WHERE
						YEAR = 2020
				) OVER (
					PARTITION BY
						COMPANY_NAME
				) - COUNT(*) FILTER (
					WHERE
						YEAR = 2019
				) OVER (
					PARTITION BY
						COMPANY_NAME
				)
			) AS NET_PRODUCTS
		FROM
			CAR_LAUNCHES
	) T