SELECT
	E.DEPARTMENT,
	E.FIRST_NAME AS EMPLOYEE_NAME,
	E.SALARY
FROM
	EMPLOYEE E
	JOIN (
		SELECT
			DEPARTMENT,
			MAX(SALARY) AS SALARY
		FROM
			EMPLOYEE
		GROUP BY
			DEPARTMENT
	) EMP_DEPT_WITH_MAX_SALARY ON E.DEPARTMENT = EMP_DEPT_WITH_MAX_SALARY.DEPARTMENT
	AND E.SALARY = EMP_DEPT_WITH_MAX_SALARY.SALARY