SELECT
	ABS(T.MAXSALARY - LAG(T.MAXSALARY, -1) OVER ()) AS SALARY_DIFFERENCE
FROM
	(
		SELECT
			MAX(SALARY) AS MAXSALARY
		FROM
			DB_EMPLOYEE E
			JOIN DB_DEPT D ON E.DEPARTMENT_ID = D.ID
		WHERE
			DEPARTMENT IN ('engineering', 'marketing')
		GROUP BY
			DEPARTMENT
	) T
LIMIT
	1