SELECT
	DATE,
	NON_PAYING,
	PAYING
FROM
	(
		SELECT DISTINCT
			ON (DATE) DATE,
			SUM(DOWNLOADS) FILTER (
				WHERE
					PAYING_CUSTOMER = 'no'
			) OVER (
				PARTITION BY
					DATE
			) AS NON_PAYING,
			SUM(DOWNLOADS) FILTER (
				WHERE
					PAYING_CUSTOMER = 'yes'
			) OVER (
				PARTITION BY
					DATE
			) AS PAYING
		FROM
			MS_USER_DIMENSION U
			JOIN MS_ACC_DIMENSION ACC ON U.ACC_ID = ACC.ACC_ID
			JOIN MS_DOWNLOAD_FACTS F ON U.USER_ID = F.USER_ID
	) T
WHERE
	NON_PAYING > PAYING