
SELECT
	EMPLOYEE_TITLE,
	SEX,
	AVG(SALARY + COALESCE(BONUS, 0)) AS AVG_COMPENSATION
FROM
	SF_EMPLOYEE E
	JOIN (
		SELECT
			WORKER_REF_ID,
			SUM(BONUS) AS BONUS
		FROM
			SF_BONUS
		GROUP BY
			(WORKER_REF_ID)
	) TOTALBONUS ON E.ID = TOTALBONUS.WORKER_REF_ID 
GROUP BY
	EMPLOYEE_TITLE,
	SEX